# Generated by Django 5.2.3 on 2025-08-14 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('public_access', models.BooleanField(default=False)),
                ('public_access_date', models.DateField(blank=True, null=True)),
                ('last_access_date', models.DateTimeField(auto_now_add=True)),
                ('diary_creation_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField(max_length=1200)),
                ('page_creation_date', models.DateTimeField(auto_now_add=True)),
                ('page_num', models.DecimalField(decimal_places=0, default=1, max_digits=1000)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='page.diary')),
            ],
            options={
                'ordering': ['page_num'],
            },
        ),
    ]
