# Generated by Django 5.2.3 on 2025-07-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='public_access_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
