# Generated by Django 5.2.3 on 2025-06-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_page_author_alter_page_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
